const TMDB_API_KEY = "5b7ab6362b64421d9a44c78fcad02dc2"; // process.env.TMDB_API_KEY;
const TMDB_API_VERSION = 3;
const TMDB_API_NEW_VERSION = 4;
const TMDB_API_READ_ACCESS_TOKEN =
  "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1YjdhYjYzNjJiNjQ0MjFkOWE0NGM3OGZjYWQwMmRjMiIsInN1YiI6IjY0MmRmNDIzYzlkYmY5MDA3NzA5NWZlOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.TqktBZqT96EwBkY1CgnfhRPnQ985R1R62uZZBRynQ9E"; // process.env.TMDB_API_READ_ACCESS_TOKEN;
const TMDB_API_BASE_URL = "https://api.themoviedb.org";
const TMDB_BASE_URL = "https://www.themoviedb.org";
const TMDB_IMAGE_BASE_URL = "https://image.tmdb.org/t/p/";
const TMDB_PAGE_LIMIT = 20;

export {
  TMDB_API_KEY,
  TMDB_API_VERSION,
  TMDB_API_NEW_VERSION,
  TMDB_API_READ_ACCESS_TOKEN,
  TMDB_API_BASE_URL,
  TMDB_BASE_URL,
  TMDB_IMAGE_BASE_URL,
  TMDB_PAGE_LIMIT,
};
